title: AI course
tagline: Deep Learning Lecture

author:
  name: Johnny Chang
  url: https://www.facebook.com/profile.php?id=100017402190747&mibextid=ZbWKwL

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 3

tags_path: /tags/
categories_path: /categories/

remote_theme: zivong/jekyll-theme-hydure
#theme: jekyll-theme-hydure
